### ISSUE TITLE
按教程使用了Vue-route之后点击按钮没有反应了？

### ISSUE THREAD

**Issue by xushaobo** [mrzhouxiaofei/Larvuent#1]

**Comment by mrzhouxiaofei** [comment]
按钮的绑定和 Vue Router 没有关系啊，问题和代码贴上来看看

**Comment by mrzhouxiaofei** [comment]
@xushaobo

**Comment by mrzhouxiaofei** [comment]
抱歉，今天看到上个问题，又走了一遍才发现是 ElementUI 的更新造成的，之前的版本可以用 v-model 的值控制对话框 el-dialog 的显示与否，现在不行了，你需要把  el-dialog 的 v-model 属性改成 :visible.sync，这样就好了
