### ISSUE TITLE
vue中 js/app.js 引入文件失败

### ISSUE THREAD

**Issue by ColorRabbit** [mrzhouxiaofei/Larvuent#2]
```
ERROR in ./resources/assets/js/app.js
Module not found: Error: Can't resolve 'element-ui/lib/theme-default/index.css' in '项目目录/resources/assets/js'
 @ ./resources/assets/js/app.js 21:0-48
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
```
我看了下在`node_modules`下`element-ui`并没有`theme-default`这个文件夹，只有`theme-chalk`文件夹，我这样引入`import 'element-ui/lib/theme-chalk/index.css';`后就成功了  系统mac，npm版本5.6.0, node v9.4.0

**Comment by mrzhouxiaofei** [comment]
感谢，我又按照文章走了一遍，确实如你所说，之前写文章的时候，ElementUI 还是 1.4 版本，现在到了 2.0 了，主题文件夹的名字也换成 theme-chalk 了，除此之外，文章测试用例中的 el-dialog 的属性也改变了，控制 el-dialog 显示与否的 v-model 也需要改成 :visible.sync 才行，晚点会更新文章，望知晓

**Comment by mrzhouxiaofei** [comment]
@ColorRabbit
